server:
  port: 8080

spring:
  application:
    name: API-Gateway

  cloud:
    gateway:
      routes:
        - id: EMAIL-SERVICE
          uri: lb://EMAIL-SERVICE
          predicates:
            - Path=/email/**
        - id: STUDENT-SERVICE
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/**,/students/**
        - id: TEACHER-SERVICE
          uri: lb://TEACHER-SERVICE
          predicates:
            - Path=/teachers/**,/teacher/**
        - id: SCHOOL-SERVICE
          uri: lb://SCHOOL-SERVICE
          predicates:
            - Path=/school/**,/schools/**,/admin/**,/admins/**
        - id: CLASS-SERVICE
          uri: lb://CLASS-SERVICE
          predicates:
            - Path=/class/**,/classes/**,/attendance/**
        - id: ISSUE-SERVICE
          uri: lb://ISSUE-SERVICE
          predicates:
            - Path=/issue/**

          


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka